# Generated by Django 3.0.2 on 2020-01-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accommo',
        ),
        migrations.DeleteModel(
            name='Taxi',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
